# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion-2019.2.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/clion-2019.2.4/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pino/pino_ale/pino_ale/Virgilium

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pino/pino_ale/pino_ale/Virgilium

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion-2019.2.4/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion-2019.2.4/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pino/pino_ale/pino_ale/Virgilium/CMakeFiles /home/pino/pino_ale/pino_ale/Virgilium/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pino/pino_ale/pino_ale/Virgilium/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named VirgiliumServer

# Build rule for target.
VirgiliumServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VirgiliumServer
.PHONY : VirgiliumServer

# fast build rule for target.
VirgiliumServer/fast:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/build
.PHONY : VirgiliumServer/fast

#=============================================================================
# Target rules for targets named VirgiliumClient

# Build rule for target.
VirgiliumClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VirgiliumClient
.PHONY : VirgiliumClient

# fast build rule for target.
VirgiliumClient/fast:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/build
.PHONY : VirgiliumClient/fast

#=============================================================================
# Target rules for targets named VirgiliumServer_autogen

# Build rule for target.
VirgiliumServer_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VirgiliumServer_autogen
.PHONY : VirgiliumServer_autogen

# fast build rule for target.
VirgiliumServer_autogen/fast:
	$(MAKE) -f CMakeFiles/VirgiliumServer_autogen.dir/build.make CMakeFiles/VirgiliumServer_autogen.dir/build
.PHONY : VirgiliumServer_autogen/fast

#=============================================================================
# Target rules for targets named VirgiliumClient_autogen

# Build rule for target.
VirgiliumClient_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VirgiliumClient_autogen
.PHONY : VirgiliumClient_autogen

# fast build rule for target.
VirgiliumClient_autogen/fast:
	$(MAKE) -f CMakeFiles/VirgiliumClient_autogen.dir/build.make CMakeFiles/VirgiliumClient_autogen.dir/build
.PHONY : VirgiliumClient_autogen/fast

VirgiliumClient_autogen/mocs_compilation.o: VirgiliumClient_autogen/mocs_compilation.cpp.o

.PHONY : VirgiliumClient_autogen/mocs_compilation.o

# target to build an object file
VirgiliumClient_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/VirgiliumClient_autogen/mocs_compilation.cpp.o
.PHONY : VirgiliumClient_autogen/mocs_compilation.cpp.o

VirgiliumClient_autogen/mocs_compilation.i: VirgiliumClient_autogen/mocs_compilation.cpp.i

.PHONY : VirgiliumClient_autogen/mocs_compilation.i

# target to preprocess a source file
VirgiliumClient_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/VirgiliumClient_autogen/mocs_compilation.cpp.i
.PHONY : VirgiliumClient_autogen/mocs_compilation.cpp.i

VirgiliumClient_autogen/mocs_compilation.s: VirgiliumClient_autogen/mocs_compilation.cpp.s

.PHONY : VirgiliumClient_autogen/mocs_compilation.s

# target to generate assembly for a file
VirgiliumClient_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/VirgiliumClient_autogen/mocs_compilation.cpp.s
.PHONY : VirgiliumClient_autogen/mocs_compilation.cpp.s

VirgiliumServer_autogen/mocs_compilation.o: VirgiliumServer_autogen/mocs_compilation.cpp.o

.PHONY : VirgiliumServer_autogen/mocs_compilation.o

# target to build an object file
VirgiliumServer_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/VirgiliumServer_autogen/mocs_compilation.cpp.o
.PHONY : VirgiliumServer_autogen/mocs_compilation.cpp.o

VirgiliumServer_autogen/mocs_compilation.i: VirgiliumServer_autogen/mocs_compilation.cpp.i

.PHONY : VirgiliumServer_autogen/mocs_compilation.i

# target to preprocess a source file
VirgiliumServer_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/VirgiliumServer_autogen/mocs_compilation.cpp.i
.PHONY : VirgiliumServer_autogen/mocs_compilation.cpp.i

VirgiliumServer_autogen/mocs_compilation.s: VirgiliumServer_autogen/mocs_compilation.cpp.s

.PHONY : VirgiliumServer_autogen/mocs_compilation.s

# target to generate assembly for a file
VirgiliumServer_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/VirgiliumServer_autogen/mocs_compilation.cpp.s
.PHONY : VirgiliumServer_autogen/mocs_compilation.cpp.s

qrc_Icons.o: qrc_Icons.cpp.o

.PHONY : qrc_Icons.o

# target to build an object file
qrc_Icons.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/qrc_Icons.cpp.o
.PHONY : qrc_Icons.cpp.o

qrc_Icons.i: qrc_Icons.cpp.i

.PHONY : qrc_Icons.i

# target to preprocess a source file
qrc_Icons.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/qrc_Icons.cpp.i
.PHONY : qrc_Icons.cpp.i

qrc_Icons.s: qrc_Icons.cpp.s

.PHONY : qrc_Icons.s

# target to generate assembly for a file
qrc_Icons.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/qrc_Icons.cpp.s
.PHONY : qrc_Icons.cpp.s

src/client/clientstuff.o: src/client/clientstuff.cpp.o

.PHONY : src/client/clientstuff.o

# target to build an object file
src/client/clientstuff.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/clientstuff.cpp.o
.PHONY : src/client/clientstuff.cpp.o

src/client/clientstuff.i: src/client/clientstuff.cpp.i

.PHONY : src/client/clientstuff.i

# target to preprocess a source file
src/client/clientstuff.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/clientstuff.cpp.i
.PHONY : src/client/clientstuff.cpp.i

src/client/clientstuff.s: src/client/clientstuff.cpp.s

.PHONY : src/client/clientstuff.s

# target to generate assembly for a file
src/client/clientstuff.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/clientstuff.cpp.s
.PHONY : src/client/clientstuff.cpp.s

src/client/server_virgilium.o: src/client/server_virgilium.cpp.o

.PHONY : src/client/server_virgilium.o

# target to build an object file
src/client/server_virgilium.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/server_virgilium.cpp.o
.PHONY : src/client/server_virgilium.cpp.o

src/client/server_virgilium.i: src/client/server_virgilium.cpp.i

.PHONY : src/client/server_virgilium.i

# target to preprocess a source file
src/client/server_virgilium.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/server_virgilium.cpp.i
.PHONY : src/client/server_virgilium.cpp.i

src/client/server_virgilium.s: src/client/server_virgilium.cpp.s

.PHONY : src/client/server_virgilium.s

# target to generate assembly for a file
src/client/server_virgilium.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/server_virgilium.cpp.s
.PHONY : src/client/server_virgilium.cpp.s

src/client/view/PersonalPage.o: src/client/view/PersonalPage.cpp.o

.PHONY : src/client/view/PersonalPage.o

# target to build an object file
src/client/view/PersonalPage.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/PersonalPage.cpp.o
.PHONY : src/client/view/PersonalPage.cpp.o

src/client/view/PersonalPage.i: src/client/view/PersonalPage.cpp.i

.PHONY : src/client/view/PersonalPage.i

# target to preprocess a source file
src/client/view/PersonalPage.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/PersonalPage.cpp.i
.PHONY : src/client/view/PersonalPage.cpp.i

src/client/view/PersonalPage.s: src/client/view/PersonalPage.cpp.s

.PHONY : src/client/view/PersonalPage.s

# target to generate assembly for a file
src/client/view/PersonalPage.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/PersonalPage.cpp.s
.PHONY : src/client/view/PersonalPage.cpp.s

src/client/view/TextEditor.o: src/client/view/TextEditor.cpp.o

.PHONY : src/client/view/TextEditor.o

# target to build an object file
src/client/view/TextEditor.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/TextEditor.cpp.o
.PHONY : src/client/view/TextEditor.cpp.o

src/client/view/TextEditor.i: src/client/view/TextEditor.cpp.i

.PHONY : src/client/view/TextEditor.i

# target to preprocess a source file
src/client/view/TextEditor.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/TextEditor.cpp.i
.PHONY : src/client/view/TextEditor.cpp.i

src/client/view/TextEditor.s: src/client/view/TextEditor.cpp.s

.PHONY : src/client/view/TextEditor.s

# target to generate assembly for a file
src/client/view/TextEditor.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/TextEditor.cpp.s
.PHONY : src/client/view/TextEditor.cpp.s

src/client/view/WelcomePage.o: src/client/view/WelcomePage.cpp.o

.PHONY : src/client/view/WelcomePage.o

# target to build an object file
src/client/view/WelcomePage.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/WelcomePage.cpp.o
.PHONY : src/client/view/WelcomePage.cpp.o

src/client/view/WelcomePage.i: src/client/view/WelcomePage.cpp.i

.PHONY : src/client/view/WelcomePage.i

# target to preprocess a source file
src/client/view/WelcomePage.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/WelcomePage.cpp.i
.PHONY : src/client/view/WelcomePage.cpp.i

src/client/view/WelcomePage.s: src/client/view/WelcomePage.cpp.s

.PHONY : src/client/view/WelcomePage.s

# target to generate assembly for a file
src/client/view/WelcomePage.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/WelcomePage.cpp.s
.PHONY : src/client/view/WelcomePage.cpp.s

src/client/view/changepassworddialog.o: src/client/view/changepassworddialog.cpp.o

.PHONY : src/client/view/changepassworddialog.o

# target to build an object file
src/client/view/changepassworddialog.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/changepassworddialog.cpp.o
.PHONY : src/client/view/changepassworddialog.cpp.o

src/client/view/changepassworddialog.i: src/client/view/changepassworddialog.cpp.i

.PHONY : src/client/view/changepassworddialog.i

# target to preprocess a source file
src/client/view/changepassworddialog.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/changepassworddialog.cpp.i
.PHONY : src/client/view/changepassworddialog.cpp.i

src/client/view/changepassworddialog.s: src/client/view/changepassworddialog.cpp.s

.PHONY : src/client/view/changepassworddialog.s

# target to generate assembly for a file
src/client/view/changepassworddialog.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/changepassworddialog.cpp.s
.PHONY : src/client/view/changepassworddialog.cpp.s

src/client/view/deletefile.o: src/client/view/deletefile.cpp.o

.PHONY : src/client/view/deletefile.o

# target to build an object file
src/client/view/deletefile.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/deletefile.cpp.o
.PHONY : src/client/view/deletefile.cpp.o

src/client/view/deletefile.i: src/client/view/deletefile.cpp.i

.PHONY : src/client/view/deletefile.i

# target to preprocess a source file
src/client/view/deletefile.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/deletefile.cpp.i
.PHONY : src/client/view/deletefile.cpp.i

src/client/view/deletefile.s: src/client/view/deletefile.cpp.s

.PHONY : src/client/view/deletefile.s

# target to generate assembly for a file
src/client/view/deletefile.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/deletefile.cpp.s
.PHONY : src/client/view/deletefile.cpp.s

src/client/view/managecollaborators.o: src/client/view/managecollaborators.cpp.o

.PHONY : src/client/view/managecollaborators.o

# target to build an object file
src/client/view/managecollaborators.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/managecollaborators.cpp.o
.PHONY : src/client/view/managecollaborators.cpp.o

src/client/view/managecollaborators.i: src/client/view/managecollaborators.cpp.i

.PHONY : src/client/view/managecollaborators.i

# target to preprocess a source file
src/client/view/managecollaborators.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/managecollaborators.cpp.i
.PHONY : src/client/view/managecollaborators.cpp.i

src/client/view/managecollaborators.s: src/client/view/managecollaborators.cpp.s

.PHONY : src/client/view/managecollaborators.s

# target to generate assembly for a file
src/client/view/managecollaborators.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/managecollaborators.cpp.s
.PHONY : src/client/view/managecollaborators.cpp.s

src/client/view/renamefile.o: src/client/view/renamefile.cpp.o

.PHONY : src/client/view/renamefile.o

# target to build an object file
src/client/view/renamefile.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/renamefile.cpp.o
.PHONY : src/client/view/renamefile.cpp.o

src/client/view/renamefile.i: src/client/view/renamefile.cpp.i

.PHONY : src/client/view/renamefile.i

# target to preprocess a source file
src/client/view/renamefile.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/renamefile.cpp.i
.PHONY : src/client/view/renamefile.cpp.i

src/client/view/renamefile.s: src/client/view/renamefile.cpp.s

.PHONY : src/client/view/renamefile.s

# target to generate assembly for a file
src/client/view/renamefile.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/renamefile.cpp.s
.PHONY : src/client/view/renamefile.cpp.s

src/client/view/renameordelete.o: src/client/view/renameordelete.cpp.o

.PHONY : src/client/view/renameordelete.o

# target to build an object file
src/client/view/renameordelete.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/renameordelete.cpp.o
.PHONY : src/client/view/renameordelete.cpp.o

src/client/view/renameordelete.i: src/client/view/renameordelete.cpp.i

.PHONY : src/client/view/renameordelete.i

# target to preprocess a source file
src/client/view/renameordelete.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/renameordelete.cpp.i
.PHONY : src/client/view/renameordelete.cpp.i

src/client/view/renameordelete.s: src/client/view/renameordelete.cpp.s

.PHONY : src/client/view/renameordelete.s

# target to generate assembly for a file
src/client/view/renameordelete.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/renameordelete.cpp.s
.PHONY : src/client/view/renameordelete.cpp.s

src/client/view/unsubscribefile.o: src/client/view/unsubscribefile.cpp.o

.PHONY : src/client/view/unsubscribefile.o

# target to build an object file
src/client/view/unsubscribefile.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/unsubscribefile.cpp.o
.PHONY : src/client/view/unsubscribefile.cpp.o

src/client/view/unsubscribefile.i: src/client/view/unsubscribefile.cpp.i

.PHONY : src/client/view/unsubscribefile.i

# target to preprocess a source file
src/client/view/unsubscribefile.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/unsubscribefile.cpp.i
.PHONY : src/client/view/unsubscribefile.cpp.i

src/client/view/unsubscribefile.s: src/client/view/unsubscribefile.cpp.s

.PHONY : src/client/view/unsubscribefile.s

# target to generate assembly for a file
src/client/view/unsubscribefile.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/view/unsubscribefile.cpp.s
.PHONY : src/client/view/unsubscribefile.cpp.s

src/client/virgilium_client.o: src/client/virgilium_client.cpp.o

.PHONY : src/client/virgilium_client.o

# target to build an object file
src/client/virgilium_client.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/virgilium_client.cpp.o
.PHONY : src/client/virgilium_client.cpp.o

src/client/virgilium_client.i: src/client/virgilium_client.cpp.i

.PHONY : src/client/virgilium_client.i

# target to preprocess a source file
src/client/virgilium_client.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/virgilium_client.cpp.i
.PHONY : src/client/virgilium_client.cpp.i

src/client/virgilium_client.s: src/client/virgilium_client.cpp.s

.PHONY : src/client/virgilium_client.s

# target to generate assembly for a file
src/client/virgilium_client.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/client/virgilium_client.cpp.s
.PHONY : src/client/virgilium_client.cpp.s

src/clientMain.o: src/clientMain.cpp.o

.PHONY : src/clientMain.o

# target to build an object file
src/clientMain.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/clientMain.cpp.o
.PHONY : src/clientMain.cpp.o

src/clientMain.i: src/clientMain.cpp.i

.PHONY : src/clientMain.i

# target to preprocess a source file
src/clientMain.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/clientMain.cpp.i
.PHONY : src/clientMain.cpp.i

src/clientMain.s: src/clientMain.cpp.s

.PHONY : src/clientMain.s

# target to generate assembly for a file
src/clientMain.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/clientMain.cpp.s
.PHONY : src/clientMain.cpp.s

src/common/CRDT/Symbol.o: src/common/CRDT/Symbol.cpp.o

.PHONY : src/common/CRDT/Symbol.o

# target to build an object file
src/common/CRDT/Symbol.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/CRDT/Symbol.cpp.o
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/CRDT/Symbol.cpp.o
.PHONY : src/common/CRDT/Symbol.cpp.o

src/common/CRDT/Symbol.i: src/common/CRDT/Symbol.cpp.i

.PHONY : src/common/CRDT/Symbol.i

# target to preprocess a source file
src/common/CRDT/Symbol.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/CRDT/Symbol.cpp.i
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/CRDT/Symbol.cpp.i
.PHONY : src/common/CRDT/Symbol.cpp.i

src/common/CRDT/Symbol.s: src/common/CRDT/Symbol.cpp.s

.PHONY : src/common/CRDT/Symbol.s

# target to generate assembly for a file
src/common/CRDT/Symbol.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/CRDT/Symbol.cpp.s
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/CRDT/Symbol.cpp.s
.PHONY : src/common/CRDT/Symbol.cpp.s

src/common/ClientSocket.o: src/common/ClientSocket.cpp.o

.PHONY : src/common/ClientSocket.o

# target to build an object file
src/common/ClientSocket.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/ClientSocket.cpp.o
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/ClientSocket.cpp.o
.PHONY : src/common/ClientSocket.cpp.o

src/common/ClientSocket.i: src/common/ClientSocket.cpp.i

.PHONY : src/common/ClientSocket.i

# target to preprocess a source file
src/common/ClientSocket.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/ClientSocket.cpp.i
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/ClientSocket.cpp.i
.PHONY : src/common/ClientSocket.cpp.i

src/common/ClientSocket.s: src/common/ClientSocket.cpp.s

.PHONY : src/common/ClientSocket.s

# target to generate assembly for a file
src/common/ClientSocket.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/ClientSocket.cpp.s
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/ClientSocket.cpp.s
.PHONY : src/common/ClientSocket.cpp.s

src/common/User.o: src/common/User.cpp.o

.PHONY : src/common/User.o

# target to build an object file
src/common/User.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/User.cpp.o
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/User.cpp.o
.PHONY : src/common/User.cpp.o

src/common/User.i: src/common/User.cpp.i

.PHONY : src/common/User.i

# target to preprocess a source file
src/common/User.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/User.cpp.i
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/User.cpp.i
.PHONY : src/common/User.cpp.i

src/common/User.s: src/common/User.cpp.s

.PHONY : src/common/User.s

# target to generate assembly for a file
src/common/User.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/User.cpp.s
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/User.cpp.s
.PHONY : src/common/User.cpp.s

src/common/messages/BasicMessage.o: src/common/messages/BasicMessage.cpp.o

.PHONY : src/common/messages/BasicMessage.o

# target to build an object file
src/common/messages/BasicMessage.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/BasicMessage.cpp.o
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/BasicMessage.cpp.o
.PHONY : src/common/messages/BasicMessage.cpp.o

src/common/messages/BasicMessage.i: src/common/messages/BasicMessage.cpp.i

.PHONY : src/common/messages/BasicMessage.i

# target to preprocess a source file
src/common/messages/BasicMessage.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/BasicMessage.cpp.i
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/BasicMessage.cpp.i
.PHONY : src/common/messages/BasicMessage.cpp.i

src/common/messages/BasicMessage.s: src/common/messages/BasicMessage.cpp.s

.PHONY : src/common/messages/BasicMessage.s

# target to generate assembly for a file
src/common/messages/BasicMessage.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/BasicMessage.cpp.s
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/BasicMessage.cpp.s
.PHONY : src/common/messages/BasicMessage.cpp.s

src/common/messages/ChangePasswordMessage.o: src/common/messages/ChangePasswordMessage.cpp.o

.PHONY : src/common/messages/ChangePasswordMessage.o

# target to build an object file
src/common/messages/ChangePasswordMessage.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/ChangePasswordMessage.cpp.o
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/ChangePasswordMessage.cpp.o
.PHONY : src/common/messages/ChangePasswordMessage.cpp.o

src/common/messages/ChangePasswordMessage.i: src/common/messages/ChangePasswordMessage.cpp.i

.PHONY : src/common/messages/ChangePasswordMessage.i

# target to preprocess a source file
src/common/messages/ChangePasswordMessage.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/ChangePasswordMessage.cpp.i
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/ChangePasswordMessage.cpp.i
.PHONY : src/common/messages/ChangePasswordMessage.cpp.i

src/common/messages/ChangePasswordMessage.s: src/common/messages/ChangePasswordMessage.cpp.s

.PHONY : src/common/messages/ChangePasswordMessage.s

# target to generate assembly for a file
src/common/messages/ChangePasswordMessage.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/ChangePasswordMessage.cpp.s
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/ChangePasswordMessage.cpp.s
.PHONY : src/common/messages/ChangePasswordMessage.cpp.s

src/common/messages/CrdtMessage.o: src/common/messages/CrdtMessage.cpp.o

.PHONY : src/common/messages/CrdtMessage.o

# target to build an object file
src/common/messages/CrdtMessage.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/CrdtMessage.cpp.o
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/CrdtMessage.cpp.o
.PHONY : src/common/messages/CrdtMessage.cpp.o

src/common/messages/CrdtMessage.i: src/common/messages/CrdtMessage.cpp.i

.PHONY : src/common/messages/CrdtMessage.i

# target to preprocess a source file
src/common/messages/CrdtMessage.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/CrdtMessage.cpp.i
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/CrdtMessage.cpp.i
.PHONY : src/common/messages/CrdtMessage.cpp.i

src/common/messages/CrdtMessage.s: src/common/messages/CrdtMessage.cpp.s

.PHONY : src/common/messages/CrdtMessage.s

# target to generate assembly for a file
src/common/messages/CrdtMessage.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/CrdtMessage.cpp.s
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/CrdtMessage.cpp.s
.PHONY : src/common/messages/CrdtMessage.cpp.s

src/common/messages/FileManagementMessage.o: src/common/messages/FileManagementMessage.cpp.o

.PHONY : src/common/messages/FileManagementMessage.o

# target to build an object file
src/common/messages/FileManagementMessage.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/FileManagementMessage.cpp.o
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/FileManagementMessage.cpp.o
.PHONY : src/common/messages/FileManagementMessage.cpp.o

src/common/messages/FileManagementMessage.i: src/common/messages/FileManagementMessage.cpp.i

.PHONY : src/common/messages/FileManagementMessage.i

# target to preprocess a source file
src/common/messages/FileManagementMessage.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/FileManagementMessage.cpp.i
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/FileManagementMessage.cpp.i
.PHONY : src/common/messages/FileManagementMessage.cpp.i

src/common/messages/FileManagementMessage.s: src/common/messages/FileManagementMessage.cpp.s

.PHONY : src/common/messages/FileManagementMessage.s

# target to generate assembly for a file
src/common/messages/FileManagementMessage.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/FileManagementMessage.cpp.s
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/FileManagementMessage.cpp.s
.PHONY : src/common/messages/FileManagementMessage.cpp.s

src/common/messages/FilesMessage.o: src/common/messages/FilesMessage.cpp.o

.PHONY : src/common/messages/FilesMessage.o

# target to build an object file
src/common/messages/FilesMessage.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/FilesMessage.cpp.o
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/FilesMessage.cpp.o
.PHONY : src/common/messages/FilesMessage.cpp.o

src/common/messages/FilesMessage.i: src/common/messages/FilesMessage.cpp.i

.PHONY : src/common/messages/FilesMessage.i

# target to preprocess a source file
src/common/messages/FilesMessage.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/FilesMessage.cpp.i
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/FilesMessage.cpp.i
.PHONY : src/common/messages/FilesMessage.cpp.i

src/common/messages/FilesMessage.s: src/common/messages/FilesMessage.cpp.s

.PHONY : src/common/messages/FilesMessage.s

# target to generate assembly for a file
src/common/messages/FilesMessage.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/FilesMessage.cpp.s
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/FilesMessage.cpp.s
.PHONY : src/common/messages/FilesMessage.cpp.s

src/common/messages/UserManagementMessage.o: src/common/messages/UserManagementMessage.cpp.o

.PHONY : src/common/messages/UserManagementMessage.o

# target to build an object file
src/common/messages/UserManagementMessage.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/UserManagementMessage.cpp.o
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/UserManagementMessage.cpp.o
.PHONY : src/common/messages/UserManagementMessage.cpp.o

src/common/messages/UserManagementMessage.i: src/common/messages/UserManagementMessage.cpp.i

.PHONY : src/common/messages/UserManagementMessage.i

# target to preprocess a source file
src/common/messages/UserManagementMessage.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/UserManagementMessage.cpp.i
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/UserManagementMessage.cpp.i
.PHONY : src/common/messages/UserManagementMessage.cpp.i

src/common/messages/UserManagementMessage.s: src/common/messages/UserManagementMessage.cpp.s

.PHONY : src/common/messages/UserManagementMessage.s

# target to generate assembly for a file
src/common/messages/UserManagementMessage.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/UserManagementMessage.cpp.s
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/UserManagementMessage.cpp.s
.PHONY : src/common/messages/UserManagementMessage.cpp.s

src/common/messages/UserMessage.o: src/common/messages/UserMessage.cpp.o

.PHONY : src/common/messages/UserMessage.o

# target to build an object file
src/common/messages/UserMessage.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/UserMessage.cpp.o
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/UserMessage.cpp.o
.PHONY : src/common/messages/UserMessage.cpp.o

src/common/messages/UserMessage.i: src/common/messages/UserMessage.cpp.i

.PHONY : src/common/messages/UserMessage.i

# target to preprocess a source file
src/common/messages/UserMessage.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/UserMessage.cpp.i
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/UserMessage.cpp.i
.PHONY : src/common/messages/UserMessage.cpp.i

src/common/messages/UserMessage.s: src/common/messages/UserMessage.cpp.s

.PHONY : src/common/messages/UserMessage.s

# target to generate assembly for a file
src/common/messages/UserMessage.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/common/messages/UserMessage.cpp.s
	$(MAKE) -f CMakeFiles/VirgiliumClient.dir/build.make CMakeFiles/VirgiliumClient.dir/src/common/messages/UserMessage.cpp.s
.PHONY : src/common/messages/UserMessage.cpp.s

src/server/Server.o: src/server/Server.cpp.o

.PHONY : src/server/Server.o

# target to build an object file
src/server/Server.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/server/Server.cpp.o
.PHONY : src/server/Server.cpp.o

src/server/Server.i: src/server/Server.cpp.i

.PHONY : src/server/Server.i

# target to preprocess a source file
src/server/Server.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/server/Server.cpp.i
.PHONY : src/server/Server.cpp.i

src/server/Server.s: src/server/Server.cpp.s

.PHONY : src/server/Server.s

# target to generate assembly for a file
src/server/Server.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/server/Server.cpp.s
.PHONY : src/server/Server.cpp.s

src/server/model/Database.o: src/server/model/Database.cpp.o

.PHONY : src/server/model/Database.o

# target to build an object file
src/server/model/Database.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/server/model/Database.cpp.o
.PHONY : src/server/model/Database.cpp.o

src/server/model/Database.i: src/server/model/Database.cpp.i

.PHONY : src/server/model/Database.i

# target to preprocess a source file
src/server/model/Database.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/server/model/Database.cpp.i
.PHONY : src/server/model/Database.cpp.i

src/server/model/Database.s: src/server/model/Database.cpp.s

.PHONY : src/server/model/Database.s

# target to generate assembly for a file
src/server/model/Database.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/server/model/Database.cpp.s
.PHONY : src/server/model/Database.cpp.s

src/server/model/Model.o: src/server/model/Model.cpp.o

.PHONY : src/server/model/Model.o

# target to build an object file
src/server/model/Model.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/server/model/Model.cpp.o
.PHONY : src/server/model/Model.cpp.o

src/server/model/Model.i: src/server/model/Model.cpp.i

.PHONY : src/server/model/Model.i

# target to preprocess a source file
src/server/model/Model.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/server/model/Model.cpp.i
.PHONY : src/server/model/Model.cpp.i

src/server/model/Model.s: src/server/model/Model.cpp.s

.PHONY : src/server/model/Model.s

# target to generate assembly for a file
src/server/model/Model.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/server/model/Model.cpp.s
.PHONY : src/server/model/Model.cpp.s

src/server/model/ServerDocument.o: src/server/model/ServerDocument.cpp.o

.PHONY : src/server/model/ServerDocument.o

# target to build an object file
src/server/model/ServerDocument.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/server/model/ServerDocument.cpp.o
.PHONY : src/server/model/ServerDocument.cpp.o

src/server/model/ServerDocument.i: src/server/model/ServerDocument.cpp.i

.PHONY : src/server/model/ServerDocument.i

# target to preprocess a source file
src/server/model/ServerDocument.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/server/model/ServerDocument.cpp.i
.PHONY : src/server/model/ServerDocument.cpp.i

src/server/model/ServerDocument.s: src/server/model/ServerDocument.cpp.s

.PHONY : src/server/model/ServerDocument.s

# target to generate assembly for a file
src/server/model/ServerDocument.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/server/model/ServerDocument.cpp.s
.PHONY : src/server/model/ServerDocument.cpp.s

src/serverMain.o: src/serverMain.cpp.o

.PHONY : src/serverMain.o

# target to build an object file
src/serverMain.cpp.o:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/serverMain.cpp.o
.PHONY : src/serverMain.cpp.o

src/serverMain.i: src/serverMain.cpp.i

.PHONY : src/serverMain.i

# target to preprocess a source file
src/serverMain.cpp.i:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/serverMain.cpp.i
.PHONY : src/serverMain.cpp.i

src/serverMain.s: src/serverMain.cpp.s

.PHONY : src/serverMain.s

# target to generate assembly for a file
src/serverMain.cpp.s:
	$(MAKE) -f CMakeFiles/VirgiliumServer.dir/build.make CMakeFiles/VirgiliumServer.dir/src/serverMain.cpp.s
.PHONY : src/serverMain.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... VirgiliumServer"
	@echo "... edit_cache"
	@echo "... VirgiliumClient"
	@echo "... VirgiliumServer_autogen"
	@echo "... VirgiliumClient_autogen"
	@echo "... VirgiliumClient_autogen/mocs_compilation.o"
	@echo "... VirgiliumClient_autogen/mocs_compilation.i"
	@echo "... VirgiliumClient_autogen/mocs_compilation.s"
	@echo "... VirgiliumServer_autogen/mocs_compilation.o"
	@echo "... VirgiliumServer_autogen/mocs_compilation.i"
	@echo "... VirgiliumServer_autogen/mocs_compilation.s"
	@echo "... qrc_Icons.o"
	@echo "... qrc_Icons.i"
	@echo "... qrc_Icons.s"
	@echo "... src/client/clientstuff.o"
	@echo "... src/client/clientstuff.i"
	@echo "... src/client/clientstuff.s"
	@echo "... src/client/server_virgilium.o"
	@echo "... src/client/server_virgilium.i"
	@echo "... src/client/server_virgilium.s"
	@echo "... src/client/view/PersonalPage.o"
	@echo "... src/client/view/PersonalPage.i"
	@echo "... src/client/view/PersonalPage.s"
	@echo "... src/client/view/TextEditor.o"
	@echo "... src/client/view/TextEditor.i"
	@echo "... src/client/view/TextEditor.s"
	@echo "... src/client/view/WelcomePage.o"
	@echo "... src/client/view/WelcomePage.i"
	@echo "... src/client/view/WelcomePage.s"
	@echo "... src/client/view/changepassworddialog.o"
	@echo "... src/client/view/changepassworddialog.i"
	@echo "... src/client/view/changepassworddialog.s"
	@echo "... src/client/view/deletefile.o"
	@echo "... src/client/view/deletefile.i"
	@echo "... src/client/view/deletefile.s"
	@echo "... src/client/view/managecollaborators.o"
	@echo "... src/client/view/managecollaborators.i"
	@echo "... src/client/view/managecollaborators.s"
	@echo "... src/client/view/renamefile.o"
	@echo "... src/client/view/renamefile.i"
	@echo "... src/client/view/renamefile.s"
	@echo "... src/client/view/renameordelete.o"
	@echo "... src/client/view/renameordelete.i"
	@echo "... src/client/view/renameordelete.s"
	@echo "... src/client/view/unsubscribefile.o"
	@echo "... src/client/view/unsubscribefile.i"
	@echo "... src/client/view/unsubscribefile.s"
	@echo "... src/client/virgilium_client.o"
	@echo "... src/client/virgilium_client.i"
	@echo "... src/client/virgilium_client.s"
	@echo "... src/clientMain.o"
	@echo "... src/clientMain.i"
	@echo "... src/clientMain.s"
	@echo "... src/common/CRDT/Symbol.o"
	@echo "... src/common/CRDT/Symbol.i"
	@echo "... src/common/CRDT/Symbol.s"
	@echo "... src/common/ClientSocket.o"
	@echo "... src/common/ClientSocket.i"
	@echo "... src/common/ClientSocket.s"
	@echo "... src/common/User.o"
	@echo "... src/common/User.i"
	@echo "... src/common/User.s"
	@echo "... src/common/messages/BasicMessage.o"
	@echo "... src/common/messages/BasicMessage.i"
	@echo "... src/common/messages/BasicMessage.s"
	@echo "... src/common/messages/ChangePasswordMessage.o"
	@echo "... src/common/messages/ChangePasswordMessage.i"
	@echo "... src/common/messages/ChangePasswordMessage.s"
	@echo "... src/common/messages/CrdtMessage.o"
	@echo "... src/common/messages/CrdtMessage.i"
	@echo "... src/common/messages/CrdtMessage.s"
	@echo "... src/common/messages/FileManagementMessage.o"
	@echo "... src/common/messages/FileManagementMessage.i"
	@echo "... src/common/messages/FileManagementMessage.s"
	@echo "... src/common/messages/FilesMessage.o"
	@echo "... src/common/messages/FilesMessage.i"
	@echo "... src/common/messages/FilesMessage.s"
	@echo "... src/common/messages/UserManagementMessage.o"
	@echo "... src/common/messages/UserManagementMessage.i"
	@echo "... src/common/messages/UserManagementMessage.s"
	@echo "... src/common/messages/UserMessage.o"
	@echo "... src/common/messages/UserMessage.i"
	@echo "... src/common/messages/UserMessage.s"
	@echo "... src/server/Server.o"
	@echo "... src/server/Server.i"
	@echo "... src/server/Server.s"
	@echo "... src/server/model/Database.o"
	@echo "... src/server/model/Database.i"
	@echo "... src/server/model/Database.s"
	@echo "... src/server/model/Model.o"
	@echo "... src/server/model/Model.i"
	@echo "... src/server/model/Model.s"
	@echo "... src/server/model/ServerDocument.o"
	@echo "... src/server/model/ServerDocument.i"
	@echo "... src/server/model/ServerDocument.s"
	@echo "... src/serverMain.o"
	@echo "... src/serverMain.i"
	@echo "... src/serverMain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

